# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=1, max_digits=8)),
                ('comment', models.TextField(max_length=32)),
                ('date', models.DateField()),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Billym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='billym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Billym'),
        ),
        migrations.AlterUniqueTogether(
            name='billym',
            unique_together=set([('owner', 'year', 'month')]),
        ),
    ]
